#!/usr/bin/env python3
"""Generate the compiled factory bank and readable catalogue from authored recipes."""
from pathlib import Path
import json, sys
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'Presets/FactoryPresets.json').read_text())
bank=data['presets']
assert len(bank)==64, 'The release bank must contain 64 presets'
assert len({p['name'].casefold() for p in bank})==64, 'Duplicate preset name'
assert len({json.dumps(p['parameters'],sort_keys=True) for p in bank})==64, 'Duplicate parameter recipe'
assert len({json.dumps({k:v for k,v in p['parameters'].items() if k not in ('output','seed')},sort_keys=True) for p in bank})==64, 'Recipes must differ beyond level or random seed'
keys=set(bank[0]['parameters'])
text=['// Generated by scripts/generate-presets.py; edit Presets/FactoryPresets.json.','#pragma once','#include "PresetLibrary.h"','inline const std::vector<wk::Preset>& factoryBank()','{','    static const std::vector<wk::Preset> bank {']
quote=lambda s:json.dumps(s,ensure_ascii=False)
for i,p in enumerate(bank):
    assert p['id']==f'factory-{i:03d}', 'Factory IDs must stay aligned with legacy host program indices'
    assert set(p['parameters'])==keys, 'Incomplete parameter set'
    values=', '.join('{ '+quote(k)+', '+str(float(v))+'f }' for k,v in p['parameters'].items())
    text.append('        { '+', '.join(quote(p[k]) for k in ('id','name','category','description'))+', { '+values+' }, '+str(i)+' },')
text+=['    };','    return bank;','}','']
header='\n'.join(text)
if '--check' in sys.argv:
    assert (root/'Source/FactoryBank.h').read_text()==header, 'FactoryBank.h is stale'
else:
    (root/'Source/FactoryBank.h').write_text(header)
    doc=['# '+data['plugin']+' Factory Presets','', '64 complete, individually authored recipes. Existing host program indices are preserved.','', '| Program | Name | Category | Usage |','|---:|---|---|---|']
    for i,p in enumerate(bank): doc.append(f"| {i+1} | {p['name']} | {p['category']} | {p['description']} |")
    (root/'Presets/CATALOG.md').write_text('\n'.join(doc)+'\n')
print(data['plugin']+': 64 unique, complete factory recipes; generated header verified' if '--check' in sys.argv else data['plugin']+': generated 64 presets')
